"""
Python & AI in Asset Management
Chapter 2 · Mathematical and Statistical Preliminaries

(c) Dr. Yves J. Hilpisch
AI-Powered by GPT 5.1
The Python Quants GmbH | https://tpq.io
https://hilpisch.com | https://linktr.ee/dyjh
"""

# %% cell 4
from __future__ import annotations

import argparse
from pathlib import Path

import numpy as np
import pandas as pd

DATA_PATH = Path("data/pyaiam_eod.csv")
if not DATA_PATH.exists():
    DATA_PATH = "https://hilpisch.com/pyaiam_eod.csv"


def write_tex_macros(path: Path, macros: dict[str, str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "% Auto-generated by code/ch02_math_stat_preliminaries.py; do not edit.",
        "",
    ]
    for name, value in macros.items():
        lines.append(rf"\newcommand{{\{name}}}{{{value}}}")
    lines.append("")
    path.write_text("\n".join(lines), encoding="utf8")


def toy_portfolio_mean_vol() -> tuple[float, float]:
    w = np.array([0.3, 0.2, 0.5])
    mu = np.array([0.08, 0.05, 0.06])
    sigma = np.array(
        [
            [0.10, 0.02, 0.01],
            [0.02, 0.05, 0.015],
            [0.01, 0.015, 0.04],
        ]
    )
    port_return = float(w @ mu)
    port_sd = float(np.sqrt(w @ sigma @ w))
    return port_return, port_sd


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(add_help=True)
    parser.add_argument(
        "--write-stats-tex",
        type=Path,
        default=None,
        help="Write LaTeX macros with key numeric results to this path and exit.",
    )
    return parser.parse_args()

args = parse_args()
if args.write_stats_tex is not None:
    port_return, port_sd = toy_portfolio_mean_vol()
    write_tex_macros(
        args.write_stats_tex,
        {
            "ChTwoToyPortReturn": f"{port_return:.3f}",
            "ChTwoToyPortVol": f"{port_sd:.3f}",
            "ChTwoToyPortReturnPct": f"{port_return * 100:.1f}" + r"\%",
            "ChTwoToyPortVolPct": f"{port_sd * 100:.1f}" + r"\%",
        },
    )
    raise SystemExit(0)

import matplotlib.pyplot as plt

plt.style.use("seaborn-v0_8")
plt.rcParams.update({"font.family": "serif", "figure.dpi": 300})



# %% cell 6
prices = pd.read_csv(DATA_PATH, parse_dates=["Date"]).set_index("Date").sort_index()
prices.head()

# %% cell 7
def compute_return_panels(price_frame: pd.DataFrame) -> tuple[pd.DataFrame,
pd.DataFrame]:
    filled = price_frame.ffill()
    log_ret = np.log(filled / filled.shift(1)).dropna()
    simple_ret = filled.pct_change().dropna()
    return log_ret, simple_ret

log_rets, simple_rets = compute_return_panels(prices)
log_rets.head()

# %% cell 9
summary_stats = pd.DataFrame({
    "mean": log_rets.mean() * 252,
    "vol": log_rets.std() * np.sqrt(252),
    "skew": log_rets.skew(),
    "kurtosis": log_rets.kurtosis(),
})
summary_stats

# %% cell 10
asset = "AAPL"
series = log_rets[asset]
fig, ax = plt.subplots(figsize=(12, 5))
series.plot(kind="hist", bins=60, density=True, alpha=0.6, label=f"{asset} log-ret")
mu, sigma = series.mean(), series.std()
x = np.linspace(series.min(), series.max(), 200)
ax.plot(x, 1 / (sigma * np.sqrt(2 * np.pi)) * np.exp(-0.5 * ((x - mu) / sigma) ** 2),
 label="Normal fit", linewidth=1.2)
ax.set_title(f"{asset} Daily Log-Return Distribution")
ax.legend()
plt.show()

# %% cell 12
port_return, port_sd = toy_portfolio_mean_vol()
print(f"Expected return: {port_return:.3f}, volatility: {port_sd:.3f}")

# %% cell 14
sample_cov = log_rets.cov() * 252
sample_cov.loc[["AAPL", "NVDA", "SPY"], ["AAPL", "NVDA", "SPY"]]

# %% cell 16
pair = ["AAPL", "TLT"]
daily_cov = log_rets[pair].cov().values
vals, vecs = np.linalg.eigh(daily_cov)
angle = np.degrees(np.arctan2(*vecs[:, 1][::-1]))
width, height = 2 * np.sqrt(vals)
fig, ax = plt.subplots(figsize=(12, 6))
ax.scatter(
    log_rets[pair[0]],
    log_rets[pair[1]],
    s=3,
    alpha=0.3,
)
ellipse = plt.matplotlib.patches.Ellipse(
    (log_rets[pair[0]].mean(), log_rets[pair[1]].mean()),
    width,
    height,
    angle=angle,
    edgecolor="crimson",
    facecolor="none",
    linewidth=1.2,
)
ax.add_patch(ellipse)
ax.set_xlabel(f"{pair[0]} log-returns")
ax.set_ylabel(f"{pair[1]} log-returns")
ax.set_title("Covariance Ellipse (AAPL vs. TLT)")
plt.show()

# %% cell 18
rng = np.random.default_rng(0)
assets = ["AAPL", "NVDA", "SPY", "GLD", "TLT"]
mu_vec = summary_stats.loc[assets, "mean"].values
cov_mat = sample_cov.loc[assets, assets].values
n_portfolios = 5000
weights = rng.dirichlet(np.ones(len(assets)), size=n_portfolios)
port_means = weights @ mu_vec
port_vols = np.sqrt(np.einsum("bi,ij,bj->b", weights, cov_mat, weights))
fig, ax = plt.subplots(figsize=(12, 5))
ax.scatter(port_vols, port_means, c=port_means / port_vols, cmap="viridis", s=6)
ax.set_xlabel("Volatility")
ax.set_ylabel("Expected Return")
ax.set_title("Monte Carlo Portfolio Cloud")
plt.show()

# %% cell 20
sample_sizes = np.arange(20, 261, 20)
means = []
true_mean = log_rets["AAPL"].mean()
rng = np.random.default_rng(42)
for n in sample_sizes:
    boot = rng.choice(log_rets["AAPL"], size=n, replace=True)
    means.append(boot.mean())
fig, ax = plt.subplots(figsize=(12, 5))
ax.plot(sample_sizes, means, marker="o", linewidth=1.1)
ax.axhline(true_mean, color="red", linestyle="--", linewidth=1)
ax.set_xlabel("Sample Size")
ax.set_ylabel("Bootstrapped Mean")
ax.set_title("Sampling Variability of Daily Mean (AAPL)")
plt.show()
